### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by slambo312** [RadCraftplay/Custom-CSGO-SDK-Launcher#114]
You haven't updated anything in a year.

**Comment by RadCraftplay** [comment]
Sorry for a very late response.

For now I do not plan adding any new features, but if there are any bugs I'll try my best to fix them.

I'm busy with university, and some features I planned like Source 2 support would require me to rewrite most of the code. If you have any specific request I might consider it, but I probably won't work on any new features until July.

**Comment by slambo312** [comment]
ok.
